config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root 'users#index'
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show] do
      resources :comments, only: %i[new create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'
  after_save :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  after_save :post_count_updater

  def post_count_updater
    author.update(posts_counter: author.posts.count)
  end

  # def recent_comments
  #   comments.order(created_at: :desc).limit(5)
  # end
  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :bio, :photo, :email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.new(author: current_user, **comment_params)
    if @comment.save
      redirect_to user_post_path(@post.author, @post), notice: 'Comment added successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: current_user.id)
    if @like.save
      redirect_to user_post_likes_path(current_user, @post)
    else
      redirect_to user_post_path(current_user, @post), alert: 'Failed to create like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @user = User.find(params[:user_id])
  #   params[:user_id]
  #   # @posts = Post.where(user_id:)
  #   @posts = @user.posts
  #   @comments = Comment.all
  # end
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = Comment.where(post_id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(title: post_params[:title], text: post_params[:text], author_id: current_user[:id],
                     comments_counter: 0, likes_counter: 0)
    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post Created Successfully'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_post
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="new_comment">
  <h2>Add New Comment</h2>
  <%= form_with(model: @comment, url: user_post_comments_path) do |f| %>
    <%= f.text_area :text, placeholder: 'Leave a comment here' %> <br>
      <%= f.submit class: 'create_comment' %>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body id = "library">
      <div id = "container">
         
         <div id = "header">
            <h1>Library Info System</h1>
            <h3>Library powered by Ruby on Rails</h3>
         </div>

         <div id = "content">
            <%= yield -%>
         </div>

         <div id = "sidebar"></div>
         
      </div>
   </body>
   
</html>

app/views/posts/index.html.erb
\<main id="posts" class="page">
  <%# Home Users, and Back buttons start %>
  <div id="user-page">
    <div class="btn-container">
      <%= link_to "Home", "../../" %>

      <div class="back-link-container">
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
      <div class="users-link-container">
        <%= link_to "Users", users_path, class: "users-link" %>
      </div>
    </div>
  </div>
  <%# End of Home, Users and Back buttons %>

  <%# user profile start %>
  <div class="user-container posts">
    <div class="user-profile-pic">
      <img src="<%= @user.photo %>" alt="profile-picture">
    </div>
    <div class="user-info">
      <h3><%= @user.name %></h3>
      <p class="posts-counter">Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
  </div>
  <%# End of user profile %>

  <article>
    <% @posts.each do |post| %>
      <%= link_to user_post_path(@user, post) do %>
        <div class="post-container">
          <h3 class="post-title"><%= post.title %></h3>
          <div class="post-details">
            <p class="details"><%= post.text[0..100]... %></p>
          </div>
          <div class="comment-like-container">
            <p class="coment-likes-data">
              Comment: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %>
            </p>
          </div>
        </div>
        <%# Post comments container start %>
        <ul class="post-comments-container">
          <% if post.recent_comments.any? %>
            <% post.recent_comments.each do |comment| %>
              <li>
                <p><%= comment.author.name %>: <%= comment.text[0..60] %>...</p>
              </li>
            <% end %>
          <% else %>
            <li>No comments added yet.</li>
          <% end %>
        </ul>
        <%# End of Post comment container %>
      <% end %>
    <% end %>
  </article>
</main>

app/views/posts/new.html.erb
<section class='create_new_post'>
  <h2>Create New Post</h2>
  <div class="back_btn_div">
    <%= link_to 'Home', root_path %>
<%= link_to 'My Page', user_path(current_user) %>
  </div>
  <div class="add_new_post">
   <%= form_with(model: @post, url: '/users/:user_id/posts' ) do |f| %>
      <%= f.label :title %>
      <div class="new_post_title">
        <%= f.text_field :title %>
      </div>
      <div class="new_post_text">
        <%= f.text_area :text, placeholder: 'Write your post here' %>
      </div>
      <%= f.submit class: 'create_post_btn' %>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<main id="post-index" class="page">
  <%# Home, Users and Back buttons start %>
  <div id="user-page">
    <div class="btn-container">
      <%= link_to "Home", "../../" %>


      <div class="back-link-container">
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
          <div class="users-link-container">
      <%= link_to "Users", users_path, class: "users-link" %>
    </div>
    </div>
    <%# End of Home, Users and Back buttons  %>
    <div class="single-post-container">
      <%# user post start %>
      <article class="post-article">
        <div class="info">
          <div>
            <h2 class="title"><%= @post.title %></h2>
            <p class="user-name">by <%= @user.name %></p>
          </div>
          <p class="posts-counter">
            Comment: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %>
          </div>
          <div class="post-body">
            <p><%= @post.text %></p>
          </div>
        </article>
        <%# End of user post %>
        <%# Comments container start %>
        <ul class="comments-container">
          <% if @comments.any?  %>
            <% @comments.each do |comment| %>
              <li>
                <p><%= User.find_by(id: comment.author_id).name %>: <%= comment.text %></p>
              </li>
            <% end %>
          <% else %>
            <li>No comments added yet...</li>
          <% end %>
        </ul>
        <%# End of Comments container  %>
      </div>
<%# start of add Comments container  %>
      <div class='add_like_comnt_div'>
<% if notice %>
  <div class="notice">
    <%= notice %>
  </div>
<% end %>
<button ><%= link_to 'Add Comment', new_user_post_comment_path(user_id: @post.author, post_id: @post.id) %></button>
<%= form_with(model: @like, url: user_post_likes_path(user_id: @post.author, post_id: @post.id) ) do |f| %>
<%= f.submit "Add Like" ,class: 'add_like_btn'%>
<% end %>
</div>

<%# end of add Comments container  %>
    </main>

app/views/users/index.html.erb
<%
=begin%>
 <h1>List of all the users</h1> 
<%
=end%>
<main id="home" class="page">
  <h1>Users</h1>
  <ul class="users-list">
    <% @users.each do |user| %>
      <li class="user-container">
        <div class="user-profile-pic">
          <%= link_to user_path(user) do %>
            <img src="<%= user.photo %>" alt="profile-picture">
          <% end %>
        </div>
        <div class="user-info">
          <h3><%= link_to user.name, user_path(user) %></h3>
          <p class="posts-counter">Number of posts: <%= user.posts_counter || 0 %></p>
        </div>
      </li>
    <% end %>
  </ul>
</main>

app/views/users/show.html.erb
<main id="user-index" class="page">
  <%# Home, Users and Back button start %>
  <div id="user-page">
      <div id="user-page">
    <div class="btn-container">
      <%= link_to "Home", "../../" %>
      <div class="back-link-container">
        <%= link_to "Back", :back, class: "back-link" %>
      </div>
          <div class="users-link-container">
      <%= link_to "Users", users_path, class: "users-link" %>
    </div>
    </div>
    <%# End of Home, Users and Back button button  %>
    <%= flash[:notice]%>
    <%# user info start here %>
    <div class="user-container">
      <div class="user-profile-pic">
        <img src="<%= @user.photo %>" alt="profile-picture">
      </div>
      <div class="user-info">
        <h3><%= @user.name%></h3>
        <p class="posts-counter">Number of posts: <%= @user.posts_counter || 0 %></p>
      </div>
    </div>
    <article class="user-bio">
      <h3>Bio</h3>
      <div class="bio"><%= @user.bio %></div>
    </article>
    <%# end of user info %>
    <%# posts start here%>
    <article>
      <% @posts.each do |post| %>
        <%= link_to  user_post_path(@user, post) do %>
          <div class="post-container">
            <h3 class="post-title"><%= post.title %></h3>
            <div class="post-details">
              <p class="details"><%= post.text[0..100]... %></p>
            </div>
            <div class="comment-like-container">
              <p class="coment-likes-data">
                Comment: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </article>
    <%# end of post %>
    <div class="btn-container see-posts">
    <%= link_to 'Create New Post', new_user_post_path(@user) %>
    </div>
    <%# see all post button %>
    <div class="btn-container see-posts">
        <%= link_to "See all posts", user_posts_path(@user) %>
    </div>
    <%# end of see all button %>
  </div>
</main>